# Generated by Django 6.1 on 2026-08-25 16:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Deep Work', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
