# Generated by Django 6.1 on 2026-09-07 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('trigger_type', models.CharField(choices=[('habit_done', 'A habit is completed'), ('all_habits_done', "All of today's habits are done"), ('streak_reached', 'A streak reaches N days'), ('goal_achieved', 'A goal is achieved'), ('daily_nudge', 'Every day at a time (optional: only if habits incomplete)')], max_length=20)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(choices=[('push', 'Send me a notification')], default='push', max_length=20)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fired_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
