# Generated by Django 6.1 on 2026-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quote', 'Quote'), ('prayer', 'Prayer'), ('philosophy', 'Philosophy')], db_index=True, max_length=20)),
                ('text', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['type'], name='content_con_type_2ac35f_idx')],
            },
        ),
    ]
