# Generated by Django 6.1 on 2026-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('quote', 'Quote'), ('prayer', 'Prayer'), ('philosophy', 'Philosophy'), ('word_of_the_day', 'Word of the Day'), ('journal_story', 'Journal Story'), ('spiritual_insight', 'Spiritual Insight')], db_index=True, max_length=30),
        ),
    ]
