# Generated by Django 6.1 on 2026-08-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentitem_image_url'),
        ('feeder', '0007_extracteditem_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='feeder_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='feeder.extracteditem'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status'], name='content_con_status_c88a23_idx'),
        ),
    ]
