# Generated by Django 6.1 on 2026-09-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_prayer_to_spiritual_insight'),
        ('feeder', '0010_extracteditem_note_extracteditem_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['type', 'status'], name='content_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'type'], name='content_status_type_idx'),
        ),
    ]
