# Generated by Django 6.1 on 2026-09-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_contentitem_content_type_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site setting',
            },
        ),
    ]
