# Generated by Django 6.1 on 2026-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(blank=True, default='check_circle', max_length=40),
        ),
    ]
