# Generated by Django 6.1 on 2026-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Paste raw text directly if not uploading a file.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='extracteditem',
            name='type',
            field=models.CharField(choices=[('quote', 'Quote'), ('prayer', 'Prayer'), ('philosophy', 'Philosophy'), ('word_of_the_day', 'Word of the Day'), ('journal_story', 'Journal Story'), ('spiritual_insight', 'Spiritual Insight')], max_length=30),
        ),
    ]
