# Generated by Django 6.1 on 2026-08-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_book_raw_text_alter_book_source_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='Anthropic API Key (sk-ant-...). Overrides environment variable if set.', max_length=255)),
                ('anthropic_model', models.CharField(default='claude-sonnet-4-5', help_text='Model identifier (e.g. claude-sonnet-4-5, claude-3-5-sonnet-20241022).', max_length=100)),
                ('chunk_size', models.PositiveIntegerField(default=800, help_text='Target character count per text chunk.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feeder Configuration',
                'verbose_name_plural': 'Feeder Configuration',
            },
        ),
    ]
