# Generated by Django 6.1 on 2026-08-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0003_feederconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='Anthropic or Gemini API Key. Overrides environment variable if set.', max_length=255)),
                ('anthropic_model', models.CharField(default='gemini-3.6-flash', help_text='Model identifier (e.g. gemini-3.6-flash, claude-sonnet-4-5).', max_length=100)),
                ('chunk_size', models.PositiveIntegerField(default=800, help_text='Target character count per text chunk.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feeder Settings',
                'verbose_name_plural': 'Feeder Settings',
            },
        ),
        migrations.DeleteModel(
            name='FeederConfig',
        ),
    ]
