# Generated by Django 6.1 on 2026-08-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0007_extracteditem_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteditem',
            name='book',
        ),
        migrations.DeleteModel(
            name='FeederSettings',
        ),
        migrations.AlterModelOptions(
            name='extracteditem',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
