# Generated by Django 6.1 on 2026-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0008_remove_extracteditem_book_delete_feedersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteditem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
