# Generated by Django 6.1 on 2026-09-07 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0009_extracteditem_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteditem',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='extracteditem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteditem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extracteditem',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extracteditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='extracteditem',
            index=models.Index(fields=['review_status'], name='feeder_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='extracteditem',
            index=models.Index(fields=['type'], name='feeder_item_type_idx'),
        ),
    ]
