# Generated by Django 6.1 on 2026-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.PositiveIntegerField(unique=True)),
                ('version_name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Short changelog shown in the app.')),
                ('apk', models.FileField(help_text='app-release.apk', upload_to='releases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version_code',),
            },
        ),
    ]
