# Generated by Django 6.1 on 2026-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='apk_url_override',
            field=models.URLField(blank=True, help_text='Fast CDN URL (e.g. GitHub Release asset). When set, the app downloads from here instead of Django/media.'),
        ),
        migrations.AlterField(
            model_name='release',
            name='apk',
            field=models.FileField(help_text='app-release.apk (legacy local hosting)', upload_to='releases/'),
        ),
    ]
