# Generated by Django 6.1 on 2026-08-25 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('time', models.TimeField()),
                ('days', models.JSONField(blank=True, default=list, help_text='0=Mon..6=Sun. Empty list means every day.')),
                ('category', models.CharField(choices=[('health', 'Health'), ('mental', 'Mental discipline'), ('financial', 'Financial'), ('progress', 'Personal progress')], default='progress', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
