# Generated by Django 6.1 on 2026-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='kind',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('streak_milestone', 'Streak milestone'), ('goal_achieved', 'Goal achieved'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
