# Generated by Django 6.1 on 2026-09-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_notificationlog_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('schedule', models.CharField(choices=[('now', 'Send once, now'), ('daily', 'Daily (every morning)'), ('weekly', 'Weekly (chosen day)')], default='now', max_length=10)),
                ('send_time', models.TimeField(default='06:30', help_text='Time of day for daily/weekly sends.')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Weekly only.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_date', models.DateField(blank=True, help_text='Dedupes same-day sends.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
